### ISSUE TITLE
이슈 노티 문제 해결법

### ISSUE THREAD

**Issue by ghaee** [ZHyoKim/SoftwareEngineering#12]
다들 이슈에 코멘트가 달리거나 했을 때에만 이메일이 오고
새로운 이슈가 등록 되었을 때에는 이메일로 노티 안 왔잖아
원인을 알아냄
![2017-11-30 12 19 52](https://user-images.githubusercontent.com/25927435/33382591-7e300f24-d564-11e7-826c-148471549443.png)
![2017-11-30 12 20 38](https://user-images.githubusercontent.com/25927435/33382595-8098d61a-d564-11e7-814c-79269dab9832.png)

이런식으로 바꿔야 온대. 다른 팀한테 물어봐서 알아낸거야 다들 한번 해봐
@ZHyoKim @Hyebin21 @jwjwPark

**Comment by jwjwPark** [comment]
오 된다 감사감사
