### ISSUE TITLE
야 근데 나 이거 진짜 궁금해. 우리 PR 안써도 되는거임?

### ISSUE THREAD

**Issue by ghaee** [ZHyoKim/SoftwareEngineering#9]
나 예전에 깃 쓸 때엔, 콜라보레이터 였어도 pull request 날리면서 작업했는데 우리 이렇게 안해도 되는거임?

포크 뜨면 -> 내 아이디/소공 이란 레포 생성 -> 작업하고 내 레포로 푸시까지 한 다음에 리모트 레포에 pull request -> 그쪽 책임자가 받아주면 내 작업 등록됨
--> 이런 식이었는데 우리 지금 이러지 않잖아.
지금 다 각자 지효/소공 레포를 공유하면서 작업하는거 맞지?  일단 작업에 무리는 없지만 pr없이 푸시만해도 되는건가 싶어서 물어봄

**Comment by ZHyoKim** [comment]
pr은 다른거잖아 pr은 collaborator가 아니니까 pr하는 거고 우리는 collaborator고 우리는 pr이 오면 받아주는 사람들인거지. 지금 과제와는 전혀 다른거야
그리고 너가 했을 때는 책임자가 한명한명 다 확인한거지 
그건 그사람이 너보다 더 높은 직급(?) 역할 인거지
